version: "3.6"

services:

  app:
    build:
      context: docker/app
      args:
        - USER_ID=${USER_ID:-1000}
        - USER_NAME=${USER_NAME:-default}
    container_name: graphql_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/app/local-cli.ini:/etc/php/7.2/cli/conf.d/99-overrides.ini
      - ./docker/app/local-fpm.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      - ./docker/app/pool.conf:/etc/php/7.2/fpm/pool.d/z-overrides.conf
      - sock-app:/run/php

  web:
    image: nginx:alpine
    container_name: graphql_web
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/web/tls:/etc/nginx/tls
      - sock-app:/run/php
    ports:
      - "${WEB_PORT:-443}:443"
      - "${WEB_PORT_H1:-80}:80"

volumes:
  sock-app:
